manifest-version = 1

[component]
name = "Amazon Data Firehose"
version = "1.1.1"

category = "data-collection"
subcategory = "warehouse"
documentation = "https://www.edgee.cloud/docs/components/data-collection/amazon-data-firehose"
repository = "https://github.com/edgee-cloud/amazon-data-firehose-component"
icon-path = "firehose.png"
wit-version = "1.0.0"
language = "Rust"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud)
and [Amazon Data Firehose](https://aws.amazon.com/firehose/),
allowing you to collect and forward analytics events to your delivery streams.

All Firehose records contain a full JSON dump of the incoming event.
'''

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && mv ./target/wasm32-wasip2/release/amazon_data_firehose_component.wasm ./firehose.wasm"
output_path = "firehose.wasm"


[component.settings.aws_access_key]
title = "Your AWS Access Key"
type = "string"
required = true
description = "It corresponds to aws_access_key_id in your credentials file."

[component.settings.aws_secret_key]
title = "Your AWS Secret Access Key"
type = "string"
required = true
description = "It corresponds to aws_secret_access_key in your credentials file."

[component.settings.aws_session_token]
title = "Your AWS Session Token (optional)"
type = "string"
description = "Useful for tests, not recommended in production because it's short-lived"

[component.settings.aws_region]
title = "Your AWS Region"
type = "string"
required = true
description = "The AWS region short name, such as us-east-1 or eu-west-1."

[component.settings.firehose_stream]
title = "Your Firehose Stream name"
type = "string"
required = true
description = "Simply the delivery stream name. Make sure to avoid leading or ending spaces."
